### ISSUE TITLE
目前的项目有继续更新的打算吗？

### ISSUE THREAD

**Issue by zealot-shin** [JiehuiSun/VIP_system#9]
大佬，你好！

 我是python 网页app开发萌新，请问这个项目您有更新的打算吗？

我这边使用manager启动后，发现页面controller貌似无法找到index以及login和register页面。不知道是我哪儿弄错了，还是项目尚未完成的原因。。

大佬有时间的话，请帮本萌新解答一下。

**Comment by yeyuguo** [comment]
是个半成品吗？

**Comment by JiehuiSun** [comment]
> 大佬，你好！
> 
> 我是python 网页app开发萌新，请问这个项目您有更新的打算吗？
> 
> 我这边使用manager启动后，发现页面controller貌似无法找到index以及login和register页面。不知道是我哪儿弄错了，还是项目尚未完成的原因。。
> 
> 大佬有时间的话，请帮本萌新解答一下。

> 你好，该项目后边由于权限问题，没有继续公开更新，目前公开的项目只是后端代码，没有web页面呢。

**Comment by JiehuiSun** [comment]
> 是个半成品吗？

> 由于权限问题没有公开更新，抱歉～

**Comment by JiehuiSun** [comment]
由于权限问题没有公开更新
